### ISSUE TITLE
Getting an error, helm-read-file-map 

### ISSUE THREAD

**Issue by Trevoke** [hatschipuh/better-helm#2]
I copied and pasted the code snippets in my config file (I also use literate programming so it was simple).

> Symbol's value as variable is void: helm-read-file-map

I've required helm; what am I missing?

**Comment by Trevoke** [comment]
Never mind - got it. The `helm-read-file-map`  variable is available after you turn on helm-mode, so somewhere in this document there probably should be `(helm-mode 1)`

**Comment by clemera** [comment]
Glad you figured it out, I should probably add some description to do that. Maybe tomorrow.
