### ISSUE TITLE
No fuzzy matching in describe-function (and some other places)

### ISSUE THREAD

**Issue by davidshepherd7** [hatschipuh/better-helm#3]
With just the settings given here you only get fuzzy matching in certain specific helm functions. You can get it in more places with:

```
(set 'helm-mode-fuzzy-match t)
```

Also thanks for compiling this tutorial, I've been wanting to move to helm for a while now but I couldn't live without flx!

**Comment by clemera** [comment]
Thanks, I will update the tutorial soon and will include that, too. Also have a look at this tip I just discovered to get [fuzzy matching everywhere](https://github.com/emacs-helm/helm/issues/145#issuecomment-151953381)

**Comment by clemera** [comment]
Tutorial updated.
