### ISSUE TITLE
Add (provide 'helm-better-defaults)?

### ISSUE THREAD

**Issue by priyadarshan** [hatschipuh/better-helm#7]
Hi,

Would it make sense to add `(provide 'helm-better-defaults)` at the end?

In that way, the file could be easily required, ie (use-package helm-better-defaults).

**Comment by clemera** [comment]
Hi, 

I will convert the guide to a package soon and add some more features as well. Then this problem will not exist anymore.

**Comment by clemera** [comment]
I just updated some things and added it as well. Thanks for noticing!

**Comment by priyadarshan** [comment]
Wonderful, thanks!
